abstract: The Catalyst developer's manual
author: Jonathan Rockway <jrockway@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Manual
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
version: 5.7011
