--- 
abstract: The Catalyst developer's manual
author: Kieren Diment <zarquon@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Manual
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
version: 5.7015
