---
abstract: "The Catalyst developer's manual"
author:
  - 'Catalyst Contributors, see Catalyst.pm'
  - 'Kieren Diment <zarquon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Manual
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Manual/5.80/trunk/
version: 5.9003
